### ISSUE TITLE
add to official redmine plugin repository

### ISSUE THREAD

**Issue by tofi86** [jbbarth/redmine_base_deface#3]
Hi,
any chance you can add this plugin to the official [redmine plugin repository](http://www.redmine.org/plugins)?
This would redmine admins to easily check all updates with recently added redmine functionality "check for plugin updates"?

Thanks! :)

**Comment by nanego** [comment]
I added the plugin to the official plugin repository:
https://www.redmine.org/plugins/redmine_base_deface

**Comment by tofi86** [comment]
Thanks! 👍
