### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by plexa16** [jbbarth/redmine_base_deface#5]
Hello,
i want to install this Plugin but it gets an error:
*\* Invoke redmine:plugins (first_time)
*\* Execute redmine:plugins
*\* Invoke redmine:plugins:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
NoMethodError: undefined method `=~' for #<Pathname:0x000000051b0b48>
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/deface-1.0.2/lib/deface/railtie.rb:50:in`block (3 levels) in class:Railtie'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/deface-1.0.2/lib/deface/railtie.rb:50:in `reject!'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/deface-1.0.2/lib/deface/railtie.rb:50:in`block (2 levels) in class:Railtie'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/deface-1.0.2/lib/deface/railtie.rb:48:in `each'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/deface-1.0.2/lib/deface/railtie.rb:48:in`block in class:Railtie'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/railties-4.2.5/lib/rails/initializable.rb:30:in`run'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:226:in`block in tsort_each'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:418:in`block (2 levels) in each_strongly_connected_component_from'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:418:in`block (2 levels) in each_strongly_connected_component_from'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:418:in`block (2 levels) in each_strongly_connected_component_from'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:418:in`block (2 levels) in each_strongly_connected_component_from'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:417:in`block in each_strongly_connected_component_from'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `each'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/railties-4.2.5/lib/rails/initializable.rb:44:in`tsort_each_child'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:411:in `call'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:411:in`each_strongly_connected_component_from'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/railties-4.2.5/lib/rails/initializable.rb:44:in`each'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `tsort_each_child'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:411:in`call'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:417:in`block in each_strongly_connected_component_from'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `each'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/railties-4.2.5/lib/rails/initializable.rb:44:in`tsort_each_child'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:411:in `call'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:411:in`each_strongly_connected_component_from'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/railties-4.2.5/lib/rails/initializable.rb:44:in`each'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `tsort_each_child'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:411:in`call'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:417:in`block in each_strongly_connected_component_from'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `each'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/railties-4.2.5/lib/rails/initializable.rb:44:in`tsort_each_child'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:411:in `call'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:411:in`each_strongly_connected_component_from'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/railties-4.2.5/lib/rails/initializable.rb:44:in`each'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `tsort_each_child'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:411:in`call'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:417:in`block in each_strongly_connected_component_from'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `each'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/railties-4.2.5/lib/rails/initializable.rb:44:in`tsort_each_child'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:411:in `call'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:411:in`each_strongly_connected_component_from'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:345:in`each'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:345:in `call'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:345:in`each_strongly_connected_component'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:205:in`tsort_each'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/railties-4.2.5/lib/rails/application.rb:352:in`initialize!'
/srv/redmine/redmine-3.2.0/config/environment.rb:14:in `<top (required)>'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/polyglot-0.3.5/lib/polyglot.rb:65:in`require'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in`block in require'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in`require'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/railties-4.2.5/lib/rails/application.rb:328:in `require_environment!'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/railties-4.2.5/lib/rails/application.rb:457:in`block in run_tasks_blocks'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/task.rb:240:in`block in execute'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/task.rb:235:in`execute'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/monitor.rb:211:in`mon_synchronize'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/task.rb:201:in`block in invoke_prerequisites'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/task.rb:199:in`invoke_prerequisites'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/monitor.rb:211:in`mon_synchronize'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/task.rb:165:in`invoke'
/srv/redmine/redmine-3.2.0/lib/tasks/redmine.rake:52:in `block (2 levels) in <top (required)>'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/task.rb:240:in`call'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/task.rb:235:in`each'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/task.rb:179:in`block in invoke_with_call_chain'
/srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/task.rb:172:in`invoke_with_call_chain'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/application.rb:150:in`invoke_task'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/application.rb:106:in`each'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/application.rb:115:in`run_with_threads'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/application.rb:78:in`block in run'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/lib/rake/application.rb:75:in`run'
/srv/redmine/.rvm/gems/ruby-2.1.4/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/srv/redmine/.rvm/gems/ruby-2.1.4/bin/rake:23:in`load'
/srv/redmine/.rvm/gems/ruby-2.1.4/bin/rake:23:in `<main>'
/srv/redmine/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in`eval'
/srv/redmine/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment

i have ruby 2.1, rails: 4.2 and redmine.3.2.0

please can u help me to fix this error

thanks

plexa16

**Comment by duke2906** [comment]
+1 Same here...

**Comment by jbbarth** [comment]
Can you post your Gemfile.lock file? (at the root of your Redmine installation)

I'll try to reproduce

**Comment by nanego** [comment]
It seems this issue has been reported here: https://github.com/spree/deface/issues/156

**Comment by nanego** [comment]
@duke2906 Do you use any other plugin? It lloks like an incompatibility with some other plugins (like redmine_extensions and easyredmine).

**Comment by duke2906** [comment]
Yeah, found out that this error will only occur if the easyredmine Plugin "ressource management" is installed... :-(

**Comment by nanego** [comment]
I think that will be fixed in the next release of the Deface gem.
