### ISSUE TITLE
Project overview shows wrong issue count

### ISSUE THREAD

**Issue by leguminator** [jbbarth/redmine_base_deface#6]
Hi,
I installed the plugin and it works pretty well.

While using it, I noticed that the project overview only shows issue count for main issues (issues created in the project). Issues from other projects are not taken in account.

Do you plan to fix this up ?
Thanks

**Comment by nanego** [comment]
Hi
I think this issue is related to the redmine_multiprojects_issue plugin, and not this base_deface plugin. Can you confirm?

**Comment by leguminator** [comment]
Damn : I thought I was on the multi-project issue plugin page.
Sorry about that
