### ISSUE TITLE
Redmine 4.0.x compatibility

### ISSUE THREAD

**Issue by srekkas** [jbbarth/redmine_base_deface#8]
Hello,
   I want to upgrade redmine to 4.0.3 version. Is this plugin compatible?

**Comment by nanego** [comment]
Hello
Yes, it's fully compatible with Redmine 4. We currently use it in production with Redmine 4.0.2.

**Comment by andreav** [comment]
Hello, It was working for me on 3.6 but after the upgrade to 4.1.1 it is no more working.
I'm using master version.

Tried also removing all other plugins, but the fields are not hidden.
